DROP TABLE IF EXISTS paragraphs;

CREATE TABLE paragraphs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    stamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    story TEXT NOT NULL
);